name: fooocus
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults

dependencies:
  # environment management
  - pip

  # from the setup script
  - pytorch-cuda=11.8
  - pytorch
  - torchvision

  # from requirements_versions.txt
  - pytorch-lightning
  - einops>=0.4.1
  - transformers>=4.30.2
  - safetensors>=0.3.1
  - accelerate>=0.21.0
  - pyyaml
  - Pillow
  - scipy
  - tqdm
  - psutil
  - numpy>=1.23.5
  - omegaconf
  - gradio
  - pygit2

  - pip:
    # pip doesn't recognize pytorch for some reason, so we install it manually
    #- torchsde>=0.2.5
    - trampoline
    - opencv-contrib-python
    # installed as part of submodule
    - -e ComfyUI
